# Usa una imagen base de PostgreSQL
FROM postgres:15

# Establece las variables de entorno para la base de datos
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=app_db

# Expone el puerto de PostgreSQL
EXPOSE 5432
