replicaCount: 2

image:
  repository: jaimehenao8126/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8081
  nodePort: 30131

ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: backend.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []