replicaCount: 1

image:
  repository: jaimehenao8126/database
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: 5432
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /readiness
    port: 5432
  initialDelaySeconds: 5
  periodSeconds: 5

kuma:
  enabled: true
  service: database # Etiqueta para Kuma
